/**
 * Unit tests for pure helpers in `util.ts`.
 *
 * Run with: `npm test` (node:test via ts-node, no EasyEDA runtime needed).
 */

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { test } from 'node:test';

import { ActionError } from './protocol';
import { classifyPinConnectivity, classifyWireConnectivity, describeThrown, filterExactLcsc, footprintMatchesInstance, footprintNameEquals, isAutoGeneratedNet, isLcscQuery, normalizeRegion, normalizeWirePoints, pickNamedCandidate, readDeviceFootprint, readLcscField, readNativeFootprintSource, THROWN_DETAIL_MAX } from './util';

test('normalizeWirePoints: flat input is returned unchanged', () => {
	assert.deepEqual(normalizeWirePoints([195, 350, 215, 350]), [195, 350, 215, 350]);
});

test('normalizeWirePoints: nested pairs are flattened', () => {
	assert.deepEqual(normalizeWirePoints([[195, 350], [215, 350]]), [195, 350, 215, 350]);
});

test('normalizeWirePoints: nested and flat yield identical create args', () => {
	const nested = normalizeWirePoints([[100, 200], [100, 300], [150, 300]]);
	const flat = normalizeWirePoints([100, 200, 100, 300, 150, 300]);
	assert.deepEqual(nested, flat);
	assert.deepEqual(flat, [100, 200, 100, 300, 150, 300]);
});

test('normalizeWirePoints: missing / empty points throws', () => {
	assert.throws(() => normalizeWirePoints(undefined), ActionError);
	assert.throws(() => normalizeWirePoints([]), ActionError);
	assert.throws(() => normalizeWirePoints('nope'), ActionError);
});

test('normalizeWirePoints: odd-length or too-short flat input throws', () => {
	assert.throws(() => normalizeWirePoints([1, 2]), ActionError); // only one point
	assert.throws(() => normalizeWirePoints([1, 2, 3]), ActionError); // odd length
});

test('normalizeWirePoints: malformed nested entry throws', () => {
	assert.throws(() => normalizeWirePoints([[1, 2], [3]]), ActionError); // not a pair
	assert.throws(() => normalizeWirePoints([[1, 2, 3], [4, 5, 6]]), ActionError); // triple
});

test('normalizeWirePoints: non-finite coordinates throw', () => {
	assert.throws(() => normalizeWirePoints([1, 2, NaN, 4]), ActionError);
	assert.throws(() => normalizeWirePoints([[1, 2], [Infinity, 4]]), ActionError);
});

test('normalizeRegion: already-ordered box is returned unchanged', () => {
	assert.deepEqual(normalizeRegion(400, 730, 300, 520), { left: 400, right: 730, top: 300, bottom: 520 });
});

test('normalizeRegion: reversed X / Y bounds are sorted to min/max', () => {
	assert.deepEqual(normalizeRegion(730, 400, 520, 300), { left: 400, right: 730, top: 300, bottom: 520 });
	assert.deepEqual(normalizeRegion(400, 730, 520, 300), { left: 400, right: 730, top: 300, bottom: 520 });
});

test('normalizeRegion: negative coordinates are supported', () => {
	assert.deepEqual(normalizeRegion(-100, -500, 50, -50), { left: -500, right: -100, top: -50, bottom: 50 });
});

test('normalizeRegion: zero-area box (collapsed axis) throws', () => {
	assert.throws(() => normalizeRegion(400, 400, 300, 520), ActionError); // x span 0
	assert.throws(() => normalizeRegion(400, 730, 300, 300), ActionError); // y span 0
});

test('normalizeRegion: non-finite bound throws', () => {
	assert.throws(() => normalizeRegion(NaN, 730, 300, 520), ActionError);
	assert.throws(() => normalizeRegion(400, Infinity, 300, 520), ActionError);
});

// ─── pickNamedCandidate (rebind footprint/symbol matcher) ─────────────

const lib = (name: string, uuid: string) => ({ name, uuid, libraryUuid: 'L1' });

test('pickNamedCandidate: exact case-sensitive single hit matches', () => {
	const res = pickNamedCandidate('QFN-32', [lib('QFN-32', 'a'), lib('QFN-48', 'b')]);
	assert.equal(res.kind, 'match');
	assert.equal(res.kind === 'match' && res.item.uuid, 'a');
});

test('pickNamedCandidate: no hit returns none (never a partial/substring match)', () => {
	const res = pickNamedCandidate('QFN', [lib('QFN-32', 'a'), lib('QFN-48', 'b')]);
	assert.equal(res.kind, 'none');
});

test('pickNamedCandidate: multiple identical names are ambiguous', () => {
	const res = pickNamedCandidate('QFN-32', [lib('QFN-32', 'a'), lib('QFN-32', 'b')]);
	assert.equal(res.kind, 'ambiguous');
	assert.deepEqual(res.kind === 'ambiguous' && res.matches.map(m => m.uuid), ['a', 'b']);
});

test('pickNamedCandidate: falls back to case-insensitive when no exact hit', () => {
	const res = pickNamedCandidate('qfn-32', [lib('QFN-32', 'a'), lib('QFN-48', 'b')]);
	assert.equal(res.kind, 'match');
	assert.equal(res.kind === 'match' && res.item.uuid, 'a');
});

test('pickNamedCandidate: case-sensitive hit wins over case-insensitive duplicates', () => {
	const res = pickNamedCandidate('QFN-32', [lib('QFN-32', 'a'), lib('qfn-32', 'b')]);
	assert.equal(res.kind, 'match');
	assert.equal(res.kind === 'match' && res.item.uuid, 'a');
});

test('pickNamedCandidate: empty candidate list returns none', () => {
	assert.equal(pickNamedCandidate('QFN-32', []).kind, 'none');
});

// ─── classifyPinConnectivity: geometry × JSON-authoritative netlist cross-check ──
// The three acceptance scenarios from issue #45, plus the netlist-muted guard.

test('classifyPinConnectivity: geometry + netlist agree connected → connected', () => {
	// netlist has a net AND geometry sees a wire.
	assert.equal(classifyPinConnectivity(true, true, true), 'connected');
});

test('classifyPinConnectivity: geom floating but netlist has net → connected (降误报 #15)', () => {
	// #15-class false positive: geometry misses the connection, netlist is authoritative.
	assert.equal(classifyPinConnectivity(true, false, true), 'connected');
});

test('classifyPinConnectivity: geom connected but netlist no net → geom-net-mismatch (补漏报)', () => {
	assert.equal(classifyPinConnectivity(false, true, true), 'geom-net-mismatch');
});

test('classifyPinConnectivity: neither source connects → floating', () => {
	assert.equal(classifyPinConnectivity(false, false, true), 'floating');
});

test('classifyPinConnectivity: netlist muted → pure geometry, never mismatch', () => {
	// getNetlistFile failed: geom-connected pins must NOT surface as mismatches.
	assert.equal(classifyPinConnectivity(false, true, false), 'connected');
	assert.equal(classifyPinConnectivity(false, false, false), 'floating');
});

test('classifyPinConnectivity: designator-less flag pin (netlist muted) + geometry wired → connected, not mismatch', () => {
	// Probe round #3: netflags/netports expose a pin "1" but never appear in the
	// netlist components map — callers mute the netlist for them (available=false).
	assert.equal(classifyPinConnectivity(false, true, false), 'connected');
});

// ── isAutoGeneratedNet ──────────────────────────────────────────────────────

test('isAutoGeneratedNet: EasyEDA $dNd single-pin net names match', () => {
	assert.equal(isAutoGeneratedNet('$3N308'), true);
	assert.equal(isAutoGeneratedNet('$12N1'), true);
	assert.equal(isAutoGeneratedNet(' $1N1 '), true); // trimmed
});

test('isAutoGeneratedNet: real net names and blanks do not match', () => {
	assert.equal(isAutoGeneratedNet('VCC'), false);
	assert.equal(isAutoGeneratedNet('GND'), false);
	assert.equal(isAutoGeneratedNet('NET$3'), false);
	assert.equal(isAutoGeneratedNet(''), false);
	assert.equal(isAutoGeneratedNet(undefined), false);
	assert.equal(isAutoGeneratedNet(null), false);
});

// ── classifyWireConnectivity (dangling-wire / issue #51) ────────────────────

test('classifyWireConnectivity: orphan stub — one end on pin, other free, auto-net → orphan-stub', () => {
	// This is the issue #51 case: connect_pin built pin→wire→flag, flag deleted,
	// stub残留. Pin end touches a pin, far end touches nothing, net is $3N308.
	const ends = [
		{ touchesPin: true, touchesMarker: false },
		{ touchesPin: false, touchesMarker: false },
	];
	assert.equal(classifyWireConnectivity(ends, '$3N308'), 'orphan-stub');
});

test('classifyWireConnectivity: one end on pin, far end free, REAL net → connected (mid-route, no false positive)', () => {
	const ends = [
		{ touchesPin: true, touchesMarker: false },
		{ touchesPin: false, touchesMarker: false },
	];
	assert.equal(classifyWireConnectivity(ends, 'VCC'), 'connected');
});

test('classifyWireConnectivity: one end on pin, far end free, BLANK net → orphan-stub (live-verified regression, 2026-07-07)', () => {
	// A connect_pin stub's wire.getState_Net() is '' on this build whether its
	// flag is intact or deleted — an INTACT stub never reaches this branch (its
	// far end touches the flag → anyMarker short-circuits to 'connected' first).
	// So reaching here with a blank net (not just the never-observed $-pattern)
	// is the real orphan signal; the original fix only checked isAutoGeneratedNet
	// and silently missed every real orphan on this build.
	const ends = [
		{ touchesPin: true, touchesMarker: false },
		{ touchesPin: false, touchesMarker: false },
	];
	assert.equal(classifyWireConnectivity(ends, ''), 'orphan-stub');
});

test('classifyWireConnectivity: far end touches a flag/port → connected regardless of net', () => {
	const ends = [
		{ touchesPin: true, touchesMarker: false },
		{ touchesPin: false, touchesMarker: true },
	];
	assert.equal(classifyWireConnectivity(ends, '$3N308'), 'connected');
});

test('classifyWireConnectivity: both ends on pins → connected pin-to-pin wire', () => {
	const ends = [
		{ touchesPin: true, touchesMarker: false },
		{ touchesPin: true, touchesMarker: false },
	];
	assert.equal(classifyWireConnectivity(ends, '$1N1'), 'connected');
});

test('classifyWireConnectivity: no end touches anything → dangling (classic)', () => {
	const ends = [
		{ touchesPin: false, touchesMarker: false },
		{ touchesPin: false, touchesMarker: false },
	];
	assert.equal(classifyWireConnectivity(ends, ''), 'dangling');
	assert.equal(classifyWireConnectivity(ends, 'VCC'), 'dangling');
});

test('isLcscQuery: bare C-numbers match (case/space tolerant)', () => {
	assert.equal(isLcscQuery('C5665'), true);
	assert.equal(isLcscQuery('c5665'), true);
	assert.equal(isLcscQuery('  C71629 '), true);
});

test('isLcscQuery: non C-number queries do not match', () => {
	assert.equal(isLcscQuery('CLC5665IMX'), false);
	assert.equal(isLcscQuery('100nF 0402'), false);
	assert.equal(isLcscQuery('C'), false);
	assert.equal(isLcscQuery('C5665 0402'), false);
});

test('readLcscField: reads supplierId, falls back to Supplier Part, else empty', () => {
	assert.equal(readLcscField({ supplierId: 'C5665' }), 'C5665');
	assert.equal(readLcscField({ otherProperty: { 'Supplier Part': 'C5665' } }), 'C5665');
	assert.equal(readLcscField({}), '');
});

test('filterExactLcsc: keeps only strict LCSC matches, drops fuzzy keyword hits', () => {
	const raw = [
		{ name: 'CLC5665IMX', supplierId: 'C123456' }, // op-amp, name contains 5665 but wrong C#
		{ name: 'IDC-TH_10P-P2.54', supplierId: 'C5665' }, // the real part
		{ name: 'other', otherProperty: { 'Supplier Part': 'c5665' } }, // migrated field, case-insensitive
		{ name: 'nope', supplierId: 'C9999' },
	];
	const out = filterExactLcsc(raw, 'C5665');
	assert.equal(out.length, 2);
	assert.deepEqual(out.map(r => r.name), ['IDC-TH_10P-P2.54', 'other']);
});

test('filterExactLcsc: empty when nothing matches the C-number', () => {
	const raw = [{ name: 'CLC5665IMX', supplierId: 'C123456' }];
	assert.deepEqual(filterExactLcsc(raw, 'C5665'), []);
});

// ─── describeThrown (#160) ────────────────────────────────────────────

test('describeThrown: Error keeps its message (the shape audit logs already showed)', () => {
	const err = new TypeError('eda.dmt_Project.getAllProjects is not a function');
	assert.equal(describeThrown(err), 'eda.dmt_Project.getAllProjects is not a function');
});

test('describeThrown: Error with empty message falls back to its name', () => {
	assert.equal(describeThrown(new RangeError('')), 'RangeError');
});

test('describeThrown: bare object is NOT flattened to [object Object]', () => {
	const detail = describeThrown({ code: 'ERR_X', message: 'boom' });
	assert.notEqual(detail, '[object Object]');
	assert.equal(detail, '[ERR_X] boom | {"code":"ERR_X","message":"boom"}');
});

test('describeThrown: message-like key is picked in precedence order', () => {
	assert.match(describeThrown({ msg: 'from msg' }), /^from msg \|/);
	assert.match(describeThrown({ error: 'from error' }), /^from error \|/);
	assert.match(describeThrown({ message: 'wins', msg: 'loses' }), /^wins \|/);
});

test('describeThrown: object without any message-like key still renders its fields', () => {
	assert.equal(describeThrown({ status: 500, path: '/x' }), '{"status":500,"path":"/x"}');
});

test('describeThrown: circular object does not throw and marks the cycle', () => {
	const cyclic: Record<string, unknown> = { name: 'loop' };
	cyclic.self = cyclic;
	const detail = describeThrown(cyclic);
	assert.match(detail, /\[Circular\]/);
	assert.notEqual(detail, '[object Object]');
});

test('describeThrown: object with no enumerable properties says so instead of [object Object]', () => {
	assert.equal(describeThrown(Object.create(null)), '[object Object] (no enumerable properties)');
});

test('describeThrown: primitives and nullish values render readably', () => {
	assert.equal(describeThrown('plain string'), 'plain string');
	assert.equal(describeThrown(null), 'null');
	assert.equal(describeThrown(undefined), 'undefined');
	assert.equal(describeThrown(42), '42');
	assert.equal(describeThrown(false), 'false');
});

test('describeThrown: oversized detail is truncated and flagged, message stays at the front', () => {
	const fat = { message: 'the readable part', blob: 'x'.repeat(5000) };
	const detail = describeThrown(fat);
	assert.ok(detail.length < 5000);
	assert.ok(detail.startsWith('the readable part'));
	assert.match(detail, /truncated, \d+ chars total/);
	assert.ok(detail.length <= THROWN_DETAIL_MAX + 40);
});

// ─── footprint identity (T-3 / T-16: package-variant mismatch on casing) ──

test('footprintNameEquals: the platform lower-cased instance name matches the library name', () => {
	assert.equal(footprintNameEquals('r0603', 'R0603'), true);
	assert.equal(
		footprintNameEquals(
			'olga-16_l3.7-w2.6-p0.50-tl_as7331-aqfm',
			'OLGA-16_L3.7-W2.6-P0.50-TL_AS7331-AQFM',
		),
		true,
	);
});

test('footprintNameEquals: surrounding whitespace is ignored', () => {
	assert.equal(footprintNameEquals('  R0603 ', 'r0603'), true);
});

test('footprintNameEquals: genuinely different packages stay unequal', () => {
	assert.equal(footprintNameEquals('R0603', 'R0805'), false);
	assert.equal(footprintNameEquals('SMBJ-LS5.4', 'SMBJ-LS5.3'), false);
});

test('footprintNameEquals: missing or empty names never match', () => {
	assert.equal(footprintNameEquals('', 'R0603'), false);
	assert.equal(footprintNameEquals('R0603', undefined), false);
	assert.equal(footprintNameEquals(undefined, undefined), false);
	assert.equal(footprintNameEquals('   ', 'R0603'), false);
});

test('footprintMatchesInstance: same footprint uuid wins over a different name', () => {
	assert.equal(
		footprintMatchesInstance(
			{ uuid: 'FP-UUID-1', name: 'r0603' },
			{ footprintUuid: 'FP-UUID-1', footprintName: 'RESISTOR-0603-RENAMED' },
		),
		true,
	);
});

test('footprintMatchesInstance: a different uuid loses even with an equal name', () => {
	assert.equal(
		footprintMatchesInstance(
			{ uuid: 'FP-UUID-1', name: 'R0603' },
			{ footprintUuid: 'FP-UUID-2', footprintName: 'R0603' },
		),
		false,
	);
});

test('footprintMatchesInstance: falls back to case-insensitive names when a uuid is absent', () => {
	assert.equal(footprintMatchesInstance({ name: 'r0603' }, { footprintName: 'R0603' }), true);
	assert.equal(
		footprintMatchesInstance({ uuid: 'FP-UUID-1', name: 'r0603' }, { footprintName: 'R0603' }),
		true,
	);
	assert.equal(footprintMatchesInstance({ name: 'r0603' }, { footprintName: 'R0805' }), false);
});

test('footprintMatchesInstance: no usable identity on either side is not a match', () => {
	assert.equal(footprintMatchesInstance(undefined, { footprintName: 'R0603' }), false);
	assert.equal(footprintMatchesInstance({ name: 'r0603' }, {}), false);
});

test('footprintMatchesInstance: nested SDK refs retain UUID and library identity', () => {
	const instance = { uuid: 'FP-1', libraryUuid: 'LIB-A', name: ' r0603 ' };
	assert.equal(footprintMatchesInstance(instance, { footprint: { uuid: 'FP-1', libraryUuid: 'LIB-A', name: 'renamed' } }), true);
	assert.equal(footprintMatchesInstance(instance, { footprint: { uuid: 'FP-2', libraryUuid: 'LIB-A', name: 'R0603' } }), false);
	assert.equal(footprintMatchesInstance(instance, { footprint: { uuid: 'FP-1', libraryUuid: 'LIB-B', name: 'R0603' } }), false);
	assert.equal(footprintMatchesInstance(instance, { footprintUuid: 'FP-1', footprintLibraryUuid: 'LIB-B', footprintName: 'R0603' }), false);
	assert.equal(footprintMatchesInstance({ name: ' r0603 ' }, { footprint: { name: ' R0603 ' } }), true);
});

test('readDeviceFootprint: official device.get association retains the 32-hex asset and its source library', () => {
	assert.deepEqual(readDeviceFootprint({ association: { footprint: { uuid: '20c29e37a9b84b4197418483096f9c05', libraryUuid: 'asset-library' } } }), {
		uuid: '20c29e37a9b84b4197418483096f9c05', libraryUuid: 'asset-library', name: '',
	});
});

// Real native FOOTPRINT rows from the Hongen project export, with user/client/
// timestamp metadata removed. Geometry and DOCHEAD→META.source are retained.
const nativeFootprintFixture = readFileSync(join(__dirname, 'testdata/hongen-footprint-source.efoo'), 'utf8');
const nativeInstanceUuid = 'abe23dba1def1246';
const nativeAssetUuid = '20c29e37a9b84b4197418483096f9c05';
const nativeAssetLibrary = '0819f05c4eef4c71ace90d822a990e87';
const nativeInventory = (source = nativeFootprintFixture) => [{ footprintUuid: nativeInstanceUuid, documentSource: source }];

test('native footprint source: captured DOCHEAD and META map the instance to its exact library asset', () => {
	assert.deepEqual(readNativeFootprintSource(nativeInventory(), nativeInstanceUuid), {
		source: { instanceUuid: nativeInstanceUuid, uuid: nativeAssetUuid, libraryUuid: nativeAssetLibrary },
	});
	assert.equal(readNativeFootprintSource(nativeInventory(nativeFootprintFixture.replaceAll('\n', '\r\n')), nativeInstanceUuid).source?.uuid, nativeAssetUuid);
	assert.equal(readNativeFootprintSource(nativeInventory(nativeFootprintFixture.trim().slice(0, -1)), nativeInstanceUuid).source?.uuid, nativeAssetUuid, 'the final native row separator is optional at EOF');
});

test('native footprint source: unrelated footprints without origin do not poison an explicit target mapping', () => {
	const inventory = [...nativeInventory(), { footprintUuid: '1111111111111111', documentSource: 'unavailable unrelated source' }];
	assert.equal(readNativeFootprintSource(inventory, nativeInstanceUuid).source?.uuid, nativeAssetUuid);
});

const nativeRows = nativeFootprintFixture.trim().split('\n');
const nativeSourceFailures: Array<[string, unknown]> = [
	['missing inventory', undefined],
	['missing target', []],
	['duplicated target inventory', [...nativeInventory(), ...nativeInventory()]],
	['wrong DOCHEAD instance', nativeInventory(nativeFootprintFixture.replace(nativeInstanceUuid, '1111111111111111'))],
	['wrong DOCHEAD domain', nativeInventory(nativeFootprintFixture.replace('"docType":"FOOTPRINT"', '"docType":"DEVICE"'))],
	['16-hex source asset', nativeInventory(nativeFootprintFixture.replace(nativeAssetUuid, nativeInstanceUuid))],
	['missing source library', nativeInventory(nativeFootprintFixture.replace(`|${nativeAssetLibrary}`, '|'))],
	['extra source token', nativeInventory(nativeFootprintFixture.replace(`|${nativeAssetLibrary}`, `|${nativeAssetLibrary}|extra`))],
	['malformed row', nativeInventory(nativeFootprintFixture + 'not a native row\n')],
	['duplicate META', nativeInventory(nativeFootprintFixture + nativeRows[nativeRows.length - 1] + '\n')],
	['META before DOCHEAD', nativeInventory([nativeRows[nativeRows.length - 1], ...nativeRows.slice(0, -1)].join('\n'))],
	['no DOCHEAD', nativeInventory(nativeRows.slice(1).join('\n'))],
	['no META', nativeInventory(nativeRows.slice(0, -1).join('\n'))],
	['source in an ATTR instead of META', nativeInventory(nativeFootprintFixture.replace('"type":"META"', '"type":"ATTR"'))],
	['multiple source documents', nativeInventory(nativeFootprintFixture + nativeFootprintFixture)],
];
for (const [reason, inventory] of nativeSourceFailures) {
	test(`native footprint source: refuses ${reason}`, () => {
		const parsed = readNativeFootprintSource(inventory, nativeInstanceUuid);
		assert.equal(parsed.source, undefined);
		assert.ok(parsed.error);
	});
}
